"use client";

import type { ConceptActivation } from "../types";

interface ActivationInsightsProps {
  viewModel: {
    sampleId: string;
    disclaimer: string;
    notes?: string;
    generatedBy?: string;
    concepts: ConceptActivation[];
  } | null;
  explanation: string | null;
  explaining: boolean;
  onExplain: () => void;
}

export function ActivationInsights({ viewModel, explanation, explaining, onExplain }: ActivationInsightsProps) {
  const hasConceptRationales = Boolean(viewModel?.concepts.some((concept) => concept.rationale));

  return (
    <section className="grid gap-6 md:grid-cols-2">
      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 shadow-lg">
        <h3 className="text-lg font-semibold text-slate-100">Narrative Context</h3>
        <div className="mt-3 space-y-3 text-sm text-slate-300">
          <p className="whitespace-pre-line text-slate-300">{viewModel?.disclaimer}</p>
          {viewModel?.notes ? <p className="rounded-lg border border-slate-800 bg-slate-950/60 p-3">{viewModel.notes}</p> : null}
          <p className="text-xs text-slate-500">
            Scenario ID: <span className="text-slate-300">{viewModel?.sampleId ?? "n/a"}</span>
          </p>
          {viewModel?.generatedBy ? (
            <p className="text-xs text-slate-500">Generated by: {viewModel.generatedBy}</p>
          ) : null}
          {hasConceptRationales ? (
            <div className="rounded-lg border border-amber-300/30 bg-amber-500/10 p-3 text-xs text-amber-100">
              <p className="font-semibold uppercase tracking-wide">Concept Insights</p>
              <ul className="mt-2 space-y-1">
                {viewModel?.concepts
                  .filter((concept) => concept.rationale)
                  .map((concept) => (
                    <li key={concept.index} className="leading-relaxed">
                      <span className="font-medium">{concept.label}:</span> {concept.rationale}
                    </li>
                  ))}
              </ul>
            </div>
          ) : null}
        </div>
      </div>
      <div className="flex flex-col gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-6 shadow-lg">
        <header className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <h3 className="text-lg font-semibold text-slate-100">Why These Synapses Fired</h3>
            <p className="text-sm text-slate-400">
              Ask the DeepSeek model to walk through this activation pattern. It will keep the speculative framing intact.
            </p>
          </div>
          <button
            type="button"
            onClick={onExplain}
            disabled={!viewModel || explaining}
            className="rounded-lg border border-amber-300 bg-amber-500/10 px-4 py-2 text-xs font-semibold text-amber-100 transition hover:bg-amber-500/20 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {explaining ? "Explaining..." : "Explain Activations"}
          </button>
        </header>
        <div className="flex-1 rounded-xl border border-slate-800 bg-slate-950/60 p-4 text-sm text-slate-200">
          {explanation ? (
            <p className="whitespace-pre-wrap leading-relaxed">{explanation}</p>
          ) : (
            <p className="text-slate-500">
              Trigger an explanation to see the assistant break down which concepts activated and why. Useful for guided
              storytelling or educational walk-throughs.
            </p>
          )}
        </div>
      </div>
    </section>
  );
}
